### PR TITLE
Fix stats bugs

### LINKED ISSUE #190: Stats -  windows icon not found
Image

### PR DESCRIPTION
**Pull request by feliciahmq**
Fixes #190 , #194 , #209 , #211 

image

No extra arguments allowed.

image

- Added an icon for the `StatisticsWindow`.
- Changed from `PieChart` to `BarChart`.
- Enabled for live update for every call for `model#getReservationStatistics` function which calls an `updateReservationStatistics`.

### CODE REVIEW

**Review by codebreaker64 — APPROVED** [review]
L🍇TM!

File: src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java [hunk 1]
```diff
@@ -91,7 +91,7 @@ public Command parseCommand(String userInput) throws ParseException {
             return new FilterCommandParser().parse(arguments);
 
         case StatisticsCommand.COMMAND_WORD:
-            return new StatisticsCommand();
+            return new StatsCommandParser().parse(arguments);
```
Comment (basil-boh) [inline src/main/java/seedu/reserve/logic/parser/ReserveMateParser.java:94]: Nice add to the parser check!

File: src/main/resources/images/bar_chart.png
Comment (basil-boh) [inline src/main/resources/images/bar_chart.png:1]: Wonderful illustration!

File: src/main/java/seedu/reserve/ui/StatisticsWindow.java [hunk 2]
```diff
@@ -103,21 +105,35 @@ public void setPieChart(HashMap<String, Integer> reservationStatistics) {
...
+            logger.fine("BarChart data set successfully.");
         }
 
+        NumberAxis yAxis = (NumberAxis) barChart.getYAxis();
+        yAxis.setAutoRanging(false);
+        yAxis.setLowerBound(0);
+        yAxis.setTickUnit(1);
+
+        // Round up maxCount to the next nice value (e.g., +1 buffer or multiple of 5)
+        int paddedUpperBound = (maxCount <= 10) ? 10 : ((maxCount + 4) / 5) * 5;
```
Comment (basil-boh) [inline src/main/java/seedu/reserve/ui/StatisticsWindow.java:134]: This method seems a bit long, I think can shorten to make this method SLAP harder

**Review by basil-boh — COMMENTED** [review]
Overall LGTM!
