### PR TITLE
Fix space issue for phone number

### LINKED ISSUE #189: Add command - phone number space not accounted for
Image

According to the error message, this phone number should be valid and accepted.

### PR DESCRIPTION
**Pull request by Kaidama97**
Allow phone numbers to have spacing.
valid phone numbers: `9 1 2 3 4 5 6 7`, `9123 4567`.

image
image

Fix #189

### CODE REVIEW

File: src/main/java/seedu/reserve/model/reservation/Phone.java [hunk 1]
```diff
@@ -22,14 +24,15 @@ public class Phone {
     public Phone(String phone) {
         requireNonNull(phone);
         checkArgument(isValidPhone(phone), MESSAGE_CONSTRAINTS);
-        value = phone;
+        value = concatPhoneNumber;
```
Comment (codebreaker64) [inline src/main/java/seedu/reserve/model/reservation/Phone.java:27]: should the value be phone instead of concatPhoneNumber? I not sure where the concatPhoneNumber comes from.

**Review by codebreaker64 — COMMENTED** [review]
Other than 1 part, the rest LGTM!

**Review by basil-boh — APPROVED** [review]
LGTM!

File: src/main/java/seedu/reserve/model/reservation/Phone.java (hunk 1 above)
Comment (basil-boh) [reply src/main/java/seedu/reserve/model/reservation/Phone.java:27]: I think isValidPhone checks if it is valid and assigns the value to concat once validated. Then concat passes the number to value to create phone object

Comment (Kaidama97) [reply src/main/java/seedu/reserve/model/reservation/Phone.java:27]: image
I editted the validation function.
