### PR TITLE
Fix occasion

### LINKED ISSUE #173: Edit Command - o/ does not display error
Image

`edit 1 o/` or `edit 1 o/  ` is allowed which should not be the case since `add` command disallows empty `o/` occasion tags, it allows only `alphanumeric`, not empty spaces.

### LINKED ISSUE #174: Edit Command - o/ allows for more than 50 characters
Image

`edit 1 o/bghkjnbghfkmngbhdsjfnbgfhjmnvbfdnfbdjnfbhdjfnbgfhjfdnbvgfdjfnbhdjnfbdjjnfbhjdnfbjdnfbhjdnfbhdjnfbhdjnfb` very long occasion names should not be allowed, as it is not allowed for name too.

Image

A similar error message should be shown for occasion `o/` tag.

### LINKED ISSUE #176: Edit Command - Ambiguity of occasion tag
The user guide says we can clear occasion tags using `o/`, however `add` command states an occasion tag must be present for a reservation. Related Issue #173 

Image

### PR DESCRIPTION
**Pull request by wowwwp**
Changes Made:
- 'o/` tag is now optional to implement
- The min length of occasion tag is 2 and the max length is 50

Behavior: (stated in the userguide)
- `add n/john p/90089008 e/jhon@gmail.com d/2025-04-04 1400 x/5` -> success
- `add n/john p/90089008 e/jhon@gmail.com d/2025-04-04 1400 x/5 o/` -> error as occasion name cannot be empty
- `edit 1 o/` -> clears reservations 

Fixes #173 
Fixes #174 
Fixes #176

### CODE REVIEW

File: src/main/java/seedu/reserve/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -60,10 +56,6 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(Messages.MESSAGE_DUPLICATE_RESERVATION);
         }
 
-        if (toAdd.getOccasions().isEmpty()) {
-            throw new CommandException(MESSAGE_OCCASION_CONSTRAINTS);
-        }
-
         model.addReservation(toAdd);
```
Comment (JohannsenLum) [inline src/main/java/seedu/reserve/logic/commands/AddCommand.java:59]: Have you tested what happens if you insert a reservation where there is no occasions inserted? can you still do edit1 o/ to insert the ocassion? or is there any error

**Review by JohannsenLum — COMMENTED** [review]
Just a minor question on the editing of ocssion, other than that, the rest of the changes looks good!

File: src/main/java/seedu/reserve/logic/commands/AddCommand.java (hunk 1 above)
Comment (wowwwp) [reply src/main/java/seedu/reserve/logic/commands/AddCommand.java:59]: it will clear any occasions present for the reservation!

**Review by basil-boh — APPROVED** [review]
LGTM
