### PR TITLE
Fix one word limitation in occasion

### LINKED ISSUE #171: Occasion Command - More than one word is not allowed
Image

`o/ Christmas Eve` returns `Tags names should be alphanumeric`.

More than one word should be allowed for occasion tags. Error message is wrong.
Occasion command needs to be updated in UG.

### PR DESCRIPTION
**Pull request by basil-boh**
This PR fixes #171 the limitation of one word inputs and now accepts multiple words & spaces in occasion description

Other changes:
* Refactored tag class to occasion

### CODE REVIEW

File: src/main/java/seedu/reserve/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -234,17 +235,17 @@ public Optional<DateTime> getDateTime() {
          * Sets {@code tags} to this object's {@code tags}.
          * A defensive copy of {@code tags} is used internally.
```
Comment (wowwwp) [inline src/main/java/seedu/reserve/logic/commands/EditCommand.java:236]: I believe the tags should be occasions here?

**Review by wowwwp — COMMENTED** [review]
lgtm!

**Review by feliciahmq — APPROVED** [review]

File: src/main/java/seedu/reserve/logic/commands/EditCommand.java (hunk 1 above)
Comment (basil-boh) [reply src/main/java/seedu/reserve/logic/commands/EditCommand.java]: Yep! thanks for the spot goat
