### PR TITLE
Branch ped bugs

### LINKED ISSUE #275: [PE-D][Tester F] Overvaluation of the format of contact number
Problem: The phone number is catered for Singapore numbers only; this may not work for numbers outside of Singapore, since the target user did not mention that they are primarily used for the Singapore context. 

Improvement: You can write it in the user guide to let the user know it is only meant for the Singapore scenario, or change phone number format from 7 to 15-digit long (based on information in Google) 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xa0412/ped#3

### LINKED ISSUE #281: [PE-D][Tester C] UG: Could include in UG to let users know that reservations are 1 hour slots
I was tinkering with the app and only found out that reservations are 1 hour slots when i added a reservation on one day and did a `free` command on that date, then i saw that the free times did not include the hour after the time i reserve.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: KimHan01/ped#1

### LINKED ISSUE #285: [PE-D][Tester B] wrong bug message
-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: HAITAO2003/ped#3

### LINKED ISSUE #305: [PE-D][Tester D] Free Command: Incorrect reporting of free time
**Issue**
Free command's time report has inconsistencies with listing the free times available. 

As seen in the screenshot, there are bookings at 2025-04-28 1800 and 2025-04-28 2000, but for the date 2025-04-28,
- the free time listed out ends at 1800 and 2000 for the first 2 ranges
- free time ends at 2300 for the last range. 

Given that there is no booking for 2025-04-28 2300, there should be some consistency between how the ranges of free time are reported in the app. 

**Ways to improve**
Settle on a standardised format of reporting the end time of each range of free time.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: pastchum/ped#6

### PR DESCRIPTION
**Pull request by codebreaker64**
Fixes #305 
FIxes #281 
FIxes #275

### CODE REVIEW

**Review by Kaidama97 — APPROVED** [review]
LGTM

**Review by wowwwp — APPROVED** [review]
lgtm

File: src/test/java/seedu/reserve/logic/commands/FreeCommandTest.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public void execute_freeSlotBeforeFirstReservation_showsEarlySlot() {
         FreeCommand freeCommand = new FreeCommand(new DateTime(TEST_DATE.toString()));
         String expectedMessage = "Available free time slots:"
                 + "\n- 2025-05-01 0000 to 2025-05-01 1200"
-                + "\n- 2025-05-01 1300 to 2025-05-01 2300";
+                + "\n- 2025-05-01 1300 to 2025-05-02 0000";
```
[the remark this answers is not in the document]
Comment (codebreaker64) [reply src/test/java/seedu/reserve/logic/commands/FreeCommandTest.java:75]: I have not merge the change yet.

File: docs/DeveloperGuide.md [hunk 2]
```diff
@@ -226,6 +226,32 @@ This section describes some noteworthy details on how certain features are imple
 
 --------------------------------------------------------------------------------------------------------------------
 
+### Delete feature
+
+The delete feature allows restaurant managers to delete any unwanted or accidental reservations. It is implemented 
+using the following
+components:
```
Comment (wowwwp) [inline docs/DeveloperGuide.md:233]: I think you should put fullstop here instead of colon bcs the header comes next

File: docs/DeveloperGuide.md [hunk 3]
```diff
@@ -226,6 +226,32 @@ This section describes some noteworthy details on how certain features are imple
...
+
+1. `DeleteCommand` - Delete the reservation based on index shown on the list.
+2. `DeleteCommandParser` - Parses and validates the user input into a `DeleteCommand` object
+
+The feature works through the following process flow:
+
+1. The user enters a command in the format `delete 1 cfm`.
+2. The `LogicManager` passes the command string to `ReserveMateParser`.
+3. `ReserveMateParser` identifies the command as a `delete` command and delegates to `DeleteCommandParser`.
+4. `DeleteCommandParser` extracts and validates the index (must be shown on the reservation list).
```
Comment (wowwwp) [inline docs/DeveloperGuide.md:247]: You can add in the parts where it throws an exception maybe add the create DeleteCommand part just for continuation

File: docs/DeveloperGuide.md [hunk 4]
```diff
@@ -1113,3 +1136,31 @@ make it difficult to differentiate between them. <br>
...
+7. **Let users define the maximum number of reservations per hourly slot**: <br>
+**Current Issue**: ReserveMate currently does not enforce a maximum number of reservations per time slot, which may not fit 
+the needs of all use cases. For instance, a venue with limited capacity might want to only allow a certain number of concurrent reservations
+during peak hours. <br>
+**Planned Enhancement**: We plan to introduce a configurable setting that allows admins or users (with the right 
+permissions) to define the maximum number of reservations allowed per hour slot. This offers greater flexibility for 
+different reservation scenarios and business rules.
+
+8. **Change free command output format to show each available hour instead of a continuous range**: <br>
+**Current Issue**: The `free` command currently displays available time in continuous ranges, e.g., `2025-04-28 0000 to 2025-04-28 1800`. While concise, this format may confuse users. They might interpret it as a single large continuous block rather than individual 1-hour slots, or be uncertain whether a reservation can be made at the ending time. <br>
```
Comment (JohannsenLum) [inline docs/DeveloperGuide.md:1149]: does this line pass the checkstyle? looks pretty long might run into more than 120 character issue

File: docs/DeveloperGuide.md [hunk 5]
```diff
@@ -1113,3 +1136,31 @@ make it difficult to differentiate between them. <br>
...
+- 2025-04-28 0000
+- 2025-04-28 0100
+  ...
+- 2025-04-28 1700
+```
+
+9. **Relax phone number constraints to support international numbers for tourists**: <br>
+**Current Issue**: The current phone number validation only accepts Singaporean numbers (8-digit numbers starting with
+8 or 9), which excludes valid international phone numbers commonly used by tourists. This limitation may prevent
+tourists from making reservations using the system. <br> **Planned Enhancement**: We plan to relax the phone number
```
Comment (JohannsenLum) [inline docs/DeveloperGuide.md:1163]: can you set **Planned Enhancement**: on a new line instead to make it format abit better!

**Review by JohannsenLum — COMMENTED** [review]
overall LGTM! just 2 minor syntax (?) issues together with Pooja's comments!

File: docs/DeveloperGuide.md (hunk 4 above)
Comment (codebreaker64) [reply docs/DeveloperGuide.md:1149]: ok updated!
